use std::env;
use std::fs;
use regex_lite::Regex;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: cstar-bind <header.h> -o <output.cx>");
        std::process::exit(1);
    }

    let input_path = &args[1];
    let mut output_path = "bindings.cx".to_string();

    let mut i = 2;
    while i < args.len() {
        if args[i] == "-o" && i + 1 < args.len() {
            output_path = args[i + 1].clone();
            i += 1;
        }
        i += 1;
    }

    let content = match fs::read_to_string(input_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("Error reading header: {}", e);
            std::process::exit(1);
        }
    };

    let re = Regex::new(r"(?m)^\s*([a-zA-Z_][a-zA-Z0-9_*]*\s+)+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^)]*)\)\s*;").unwrap();

    let mut cx_code = String::new();
    cx_code.push_str("// Generated by cstar-bind\n\n");

    for cap in re.captures_iter(&content) {
        let ret_and_modifiers = cap.get(1).unwrap().as_str().trim();
        let func_name = cap.get(2).unwrap().as_str().trim();
        let args_str = cap.get(3).unwrap().as_str().trim();

        let cstar_ret = map_c_type(ret_and_modifiers);

        let mut cstar_args = Vec::new();
        if !args_str.is_empty() && args_str != "void" {
            for arg in args_str.split(',') {
                let parts: Vec<&str> = arg.split_whitespace().collect();
                if parts.len() >= 2 {
                    let c_type = parts[..parts.len()-1].join(" ");
                    let param_name = parts.last().unwrap().trim_matches('*');
                    let cstar_type = map_c_type(&c_type);
                    cstar_args.push(format!("{}: {}", param_name, cstar_type));
                }
            }
        }

        let ret_sig = if cstar_ret.is_empty() {
            "".to_string()
        } else {
            format!(" -> {}", cstar_ret)
        };

        cx_code.push_str(&format!(
            "pub fn {}({}){} {{\n",
            func_name,
            cstar_args.join(", "),
            ret_sig
        ));

        if cstar_ret == "f64" {
            cx_code.push_str("    0.0\n");
        } else if cstar_ret == "i32" {
            cx_code.push_str("    0\n");
        } else if !cstar_ret.is_empty() {
            cx_code.push_str("    raw {\n        return 0\n    }\n");
        }
        cx_code.push_str("}\n\n");
    }

    if let Err(e) = fs::write(&output_path, cx_code) {
        eprintln!("Error writing bindings: {}", e);
        std::process::exit(1);
    }

    println!("Generated C* bindings successfully at {}", output_path);
}

fn map_c_type(c_type: &str) -> &'static str {
    let t = c_type.trim();
    if t.contains("double") {
        "f64"
    } else if t.contains("float") {
        "f32"
    } else if t.contains("int") {
        "i32"
    } else if t.contains("char") {
        if t.contains('*') {
            "raw *u8"
        } else {
            "u8"
        }
    } else if t.contains("void") {
        ""
    } else {
        "i32" // default fallback
    }
}
